#!/usr/bin/env bash
# =============================================================================
# PowerKit Defaults Configuration - KISS/DRY Version
# =============================================================================
# All default values for PowerKit. Users override via tmux.conf options.
# shellcheck disable=SC2034
#
# GLOBAL VARIABLES EXPORTED:
#   - All POWERKIT_* variables (configuration defaults)
#   - _DEFAULT_* variables (base defaults for DRY)
#
# DEPENDENCIES: source_guard.sh
# =============================================================================

# Source guard
_DEFAULTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=src/source_guard.sh
. "$_DEFAULTS_DIR/source_guard.sh"
source_guard "defaults" && return 0

# =============================================================================
# BASE DEFAULTS (DRY - reused across plugins)
# =============================================================================

_DEFAULT_CACHE_DIRECTORY=tmux-powerkit

# Default colors (semantic names)
_DEFAULT_ACCENT="active"
_DEFAULT_ACCENT_ICON="secondary"
_DEFAULT_SUCCESS="success"
_DEFAULT_SUCCESS_ICON="success-subtle"
_DEFAULT_INFO="info"
_DEFAULT_INFO_ICON="info-subtle"
_DEFAULT_WARNING="warning"
_DEFAULT_WARNING_ICON="warning-subtle"
_DEFAULT_ERROR="error"
_DEFAULT_ERROR_ICON="error-subtle"

# Default thresholds
_DEFAULT_WARNING_THRESHOLD="70"
_DEFAULT_CRITICAL_THRESHOLD="90"

# Common values
_DEFAULT_SEPARATOR=" | "
_DEFAULT_MAX_LENGTH="40"
_DEFAULT_POPUP_SIZE="50%"

# Common timeouts and TTLs (in seconds)
_DEFAULT_TIMEOUT_SHORT="5"
_DEFAULT_TIMEOUT_MEDIUM="10"
_DEFAULT_TIMEOUT_LONG="30"
_DEFAULT_CACHE_TTL_SHORT="60"         # 1 minute
_DEFAULT_CACHE_TTL_MEDIUM="300"       # 5 minutes
_DEFAULT_CACHE_TTL_LONG="3600"        # 1 hour
_DEFAULT_CACHE_TTL_DAY="86400"        # 24 hours

# =============================================================================
# PLUGIN DEFAULTS HELPER (DRY)
# =============================================================================
# Automatically sets standard plugin variables if not already defined.
# Call after defining plugin-specific overrides.
#
# Usage: _plugin_defaults "pluginname" [has_thresholds]
# =============================================================================

_plugin_defaults() {
    local name="${1^^}"  # uppercase
    name="${name//-/_}"  # replace - with _
    local has_thresholds="${2:-}"

    local prefix="POWERKIT_PLUGIN_${name}"

    # Standard colors (set if not defined)
    local accent_var="${prefix}_ACCENT_COLOR"
    local accent_icon_var="${prefix}_ACCENT_COLOR_ICON"
    [[ -z "${!accent_var:-}" ]] && eval "${accent_var}=\"\$_DEFAULT_ACCENT\""
    [[ -z "${!accent_icon_var:-}" ]] && eval "${accent_icon_var}=\"\$_DEFAULT_ACCENT_ICON\""

    # Threshold colors (only if plugin uses thresholds)
    if [[ -n "$has_thresholds" ]]; then
        local warn_var="${prefix}_WARNING_ACCENT_COLOR"
        local warn_icon_var="${prefix}_WARNING_ACCENT_COLOR_ICON"
        local crit_var="${prefix}_CRITICAL_ACCENT_COLOR"
        local crit_icon_var="${prefix}_CRITICAL_ACCENT_COLOR_ICON"

        [[ -z "${!warn_var:-}" ]] && eval "${warn_var}=\"\$_DEFAULT_WARNING\""
        [[ -z "${!warn_icon_var:-}" ]] && eval "${warn_icon_var}=\"\$_DEFAULT_WARNING_ICON\""
        [[ -z "${!crit_var:-}" ]] && eval "${crit_var}=\"\$_DEFAULT_ERROR\""
        [[ -z "${!crit_icon_var:-}" ]] && eval "${crit_icon_var}=\"\$_DEFAULT_ERROR_ICON\""
    fi
}

# Get plugin default value by name
# Usage: get_powerkit_plugin_default "battery" "icon"
get_powerkit_plugin_default() {
    local var_name="POWERKIT_PLUGIN_${1^^}_${2^^}"
    var_name="${var_name//-/_}"
    printf '%s' "${!var_name:-}"
}
get_plugin_default() { get_powerkit_plugin_default "$@"; }

# =============================================================================
# CORE OPTIONS
# =============================================================================

POWERKIT_DEFAULT_THEME="tokyo-night"
POWERKIT_DEFAULT_THEME_VARIANT="night"
POWERKIT_DEFAULT_DISABLE_PLUGINS=0
POWERKIT_DEFAULT_BAR_LAYOUT="single"
POWERKIT_DEFAULT_TRANSPARENT="false"
POWERKIT_DEFAULT_PLUGINS="datetime,hostname,git,battery,cpu,memory"
POWERKIT_DEFAULT_STATUS_LEFT_LENGTH="100"
POWERKIT_DEFAULT_STATUS_RIGHT_LENGTH="1000"

# =============================================================================
# SEPARATORS
# =============================================================================

POWERKIT_DEFAULT_SEPARATOR_STYLE="rounded"
POWERKIT_DEFAULT_LEFT_SEPARATOR=$'\ue0b0'
POWERKIT_DEFAULT_RIGHT_SEPARATOR=$'\ue0b2'
POWERKIT_DEFAULT_RIGHT_SEPARATOR_INVERSE=$'\ue0b3'
POWERKIT_DEFAULT_LEFT_SEPARATOR_ROUNDED=$'\ue0b6'
POWERKIT_DEFAULT_RIGHT_SEPARATOR_ROUNDED=$'\ue0b4'

# =============================================================================
# SESSION & WINDOW
# =============================================================================

POWERKIT_DEFAULT_SESSION_ICON="auto"
POWERKIT_DEFAULT_SESSION_PREFIX_COLOR="warning"
POWERKIT_DEFAULT_SESSION_COPY_MODE_COLOR="info"
POWERKIT_DEFAULT_SESSION_NORMAL_COLOR="success"
POWERKIT_DEFAULT_ACTIVE_WINDOW_ICON=$'\ue795'
POWERKIT_DEFAULT_INACTIVE_WINDOW_ICON=$'\uf489'
POWERKIT_DEFAULT_ZOOMED_WINDOW_ICON=$'\uf531'
POWERKIT_DEFAULT_PANE_SYNCHRONIZED_ICON="✵"
POWERKIT_DEFAULT_ACTIVE_WINDOW_TITLE="#W "
POWERKIT_DEFAULT_INACTIVE_WINDOW_TITLE="#W "
POWERKIT_DEFAULT_WINDOW_WITH_ACTIVITY_STYLE="italics"
POWERKIT_DEFAULT_ACTIVE_WINDOW_NUMBER_BG="accent"
POWERKIT_DEFAULT_INACTIVE_WINDOW_NUMBER_BG="border-subtle"
POWERKIT_DEFAULT_ACTIVE_PANE_BORDER_STYLE="border-strong"
POWERKIT_DEFAULT_INACTIVE_PANE_BORDER_STYLE="surface"
POWERKIT_DEFAULT_ACTIVE_WINDOW_CONTENT_BG="primary"
POWERKIT_DEFAULT_STATUS_BELL_STYLE="bold"

# =============================================================================
# HELPER KEYBINDINGS
# =============================================================================
# Mnemonic Ctrl keybindings (prefix + Ctrl+KEY)
# Reserved: C-a(prefix), C-b(prefix), C-h/j/k/l(vim), C-n/p(windows), C-o(rotate), C-z(suspend)
# Free keys: C-d, C-e, C-f, C-g, C-q, C-r, C-s, C-u, C-v, C-y
# =============================================================================

# Options viewer (prefix + Ctrl+e for sEttings/options) - free key
POWERKIT_DEFAULT_OPTIONS_KEY="C-e"
POWERKIT_DEFAULT_OPTIONS_WIDTH="80%"
POWERKIT_DEFAULT_OPTIONS_HEIGHT="80%"

# Keybindings viewer (prefix + Ctrl+y for keYs) - free key
POWERKIT_DEFAULT_KEYBINDINGS_KEY="C-y"
POWERKIT_DEFAULT_KEYBINDINGS_WIDTH="80%"
POWERKIT_DEFAULT_KEYBINDINGS_HEIGHT="80%"

# Theme selector (prefix + Ctrl+r for Retheme/change theme) - free key
POWERKIT_DEFAULT_THEME_SELECTOR_KEY="C-r"

# =============================================================================
# PLUGINS
# =============================================================================
# Only plugin-specific values are defined. Standard colors are inherited
# via _plugin_defaults() at the end of this file.
# =============================================================================

# --- audiodevices ---
POWERKIT_PLUGIN_AUDIODEVICES_ICON=$'\uf025'
POWERKIT_PLUGIN_AUDIODEVICES_INPUT_ICON=$'\uf130'
POWERKIT_PLUGIN_AUDIODEVICES_OUTPUT_ICON=$'\uf028'
POWERKIT_PLUGIN_AUDIODEVICES_SHOW="both"
POWERKIT_PLUGIN_AUDIODEVICES_SEPARATOR="$_DEFAULT_SEPARATOR"
POWERKIT_PLUGIN_AUDIODEVICES_CACHE_TTL="15"
POWERKIT_PLUGIN_AUDIODEVICES_MAX_LENGTH="15"
# Audio: C-q for inQut (input), C-u for oUtput - free keys
POWERKIT_PLUGIN_AUDIODEVICES_INPUT_KEY="C-q"
POWERKIT_PLUGIN_AUDIODEVICES_OUTPUT_KEY="C-u"

# --- battery ---
POWERKIT_PLUGIN_BATTERY_ICON="󰁹"
POWERKIT_PLUGIN_BATTERY_ICON_LOW="󰂃"
POWERKIT_PLUGIN_BATTERY_ICON_CHARGING="󰂄"
POWERKIT_PLUGIN_BATTERY_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_BATTERY_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_BATTERY_CACHE_TTL="60"
POWERKIT_PLUGIN_BATTERY_DISPLAY_MODE="percentage"
POWERKIT_PLUGIN_BATTERY_LOW_THRESHOLD="30"
POWERKIT_PLUGIN_BATTERY_LOW_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_BATTERY_LOW_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"
POWERKIT_PLUGIN_BATTERY_MID_THRESHOLD="50"
POWERKIT_PLUGIN_BATTERY_MID_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_BATTERY_MID_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
# Note: Using "MID" instead of "WARNING" to avoid conflict with automatic threshold system

# --- bitwarden ---
POWERKIT_PLUGIN_BITWARDEN_ICON=$'\uf132'
POWERKIT_PLUGIN_BITWARDEN_ICON_UNLOCKED=$'\uf09c'
POWERKIT_PLUGIN_BITWARDEN_ICON_LOCKED=$'\uf023'
POWERKIT_PLUGIN_BITWARDEN_ICON_LOGGED_OUT=$'\uf071'
POWERKIT_PLUGIN_BITWARDEN_CACHE_TTL="30"
POWERKIT_PLUGIN_BITWARDEN_SHOW_WHEN_LOCKED="true"
POWERKIT_PLUGIN_BITWARDEN_SHOW_WHEN_UNLOCKED="true"
# Bitwarden keybindings
POWERKIT_PLUGIN_BITWARDEN_PASSWORD_SELECTOR_KEY="C-v"  # prefix + C-v: select password from vault
POWERKIT_PLUGIN_BITWARDEN_PASSWORD_SELECTOR_WIDTH="60%"
POWERKIT_PLUGIN_BITWARDEN_PASSWORD_SELECTOR_HEIGHT="80%"
POWERKIT_PLUGIN_BITWARDEN_UNLOCK_KEY="C-w"             # prefix + C-w: unlock vault (Warden)
POWERKIT_PLUGIN_BITWARDEN_UNLOCK_WIDTH="40%"
POWERKIT_PLUGIN_BITWARDEN_UNLOCK_HEIGHT="40%"
POWERKIT_PLUGIN_BITWARDEN_LOCK_KEY=""                        # Disabled by default (set to "C-l" to enable)
POWERKIT_PLUGIN_BITWARDEN_TOTP_SELECTOR_KEY=""               # Disabled by default - TOTP requires Premium (set to "C-t" to enable)
POWERKIT_PLUGIN_BITWARDEN_TOTP_SELECTOR_WIDTH="60%"
POWERKIT_PLUGIN_BITWARDEN_TOTP_SELECTOR_HEIGHT="80%"
POWERKIT_PLUGIN_BITWARDEN_UNLOCKED_ACCENT_COLOR="$_DEFAULT_SUCCESS"
POWERKIT_PLUGIN_BITWARDEN_UNLOCKED_ACCENT_COLOR_ICON="$_DEFAULT_SUCCESS_ICON"
POWERKIT_PLUGIN_BITWARDEN_LOCKED_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_BITWARDEN_LOCKED_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_BITWARDEN_LOGGED_OUT_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_BITWARDEN_LOGGED_OUT_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"

# --- bluetooth ---
POWERKIT_PLUGIN_BLUETOOTH_ICON="󰂯"
POWERKIT_PLUGIN_BLUETOOTH_ICON_OFF="󰂲"
POWERKIT_PLUGIN_BLUETOOTH_ICON_CONNECTED="󰂱"
POWERKIT_PLUGIN_BLUETOOTH_OFF_ACCENT_COLOR="disabled"
POWERKIT_PLUGIN_BLUETOOTH_OFF_ACCENT_COLOR_ICON="disabled"
POWERKIT_PLUGIN_BLUETOOTH_CONNECTED_ACCENT_COLOR="$_DEFAULT_SUCCESS"
POWERKIT_PLUGIN_BLUETOOTH_CONNECTED_ACCENT_COLOR_ICON="$_DEFAULT_SUCCESS_ICON"
POWERKIT_PLUGIN_BLUETOOTH_SHOW_DEVICE="true"
POWERKIT_PLUGIN_BLUETOOTH_SHOW_BATTERY="true"
POWERKIT_PLUGIN_BLUETOOTH_BATTERY_TYPE="min"
POWERKIT_PLUGIN_BLUETOOTH_FORMAT="all"
POWERKIT_PLUGIN_BLUETOOTH_MAX_LENGTH="$_DEFAULT_MAX_LENGTH"
POWERKIT_PLUGIN_BLUETOOTH_CACHE_TTL="30"

# --- brightness ---
POWERKIT_PLUGIN_BRIGHTNESS_ICON="󰤞"
POWERKIT_PLUGIN_BRIGHTNESS_ICON_LOW="󰤚"
POWERKIT_PLUGIN_BRIGHTNESS_ICON_MEDIUM="󰤝"
POWERKIT_PLUGIN_BRIGHTNESS_ICON_HIGH="󰤞"
POWERKIT_PLUGIN_BRIGHTNESS_CACHE_TTL="10"

# --- camera ---
POWERKIT_PLUGIN_CAMERA_ICON=$'\uf030'
POWERKIT_PLUGIN_CAMERA_ACTIVE_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_CAMERA_ACTIVE_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"
POWERKIT_PLUGIN_CAMERA_SHOW="on"
POWERKIT_PLUGIN_CAMERA_CACHE_TTL="2"
POWERKIT_PLUGIN_CAMERA_SHOW_WHEN_INACTIVE="false"

# --- cloud ---
POWERKIT_PLUGIN_CLOUD_ICON=$'\uf0c2'
POWERKIT_PLUGIN_CLOUD_ICON_AWS=$'\ue7ad'
POWERKIT_PLUGIN_CLOUD_ICON_GCP=$'\ue7f1'
POWERKIT_PLUGIN_CLOUD_ICON_AZURE=$'\ue754'
POWERKIT_PLUGIN_CLOUD_ICON_MULTI="☁️"
POWERKIT_PLUGIN_CLOUD_PROD_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_CLOUD_PROVIDERS="all"
POWERKIT_PLUGIN_CLOUD_FORMAT="short"
POWERKIT_PLUGIN_CLOUD_SHOW_ACCOUNT="false"
POWERKIT_PLUGIN_CLOUD_SHOW_REGION="true"
POWERKIT_PLUGIN_CLOUD_MAX_LENGTH="$_DEFAULT_MAX_LENGTH"
POWERKIT_PLUGIN_CLOUD_SEPARATOR="$_DEFAULT_SEPARATOR"
POWERKIT_PLUGIN_CLOUD_WARN_ON_PROD="true"
POWERKIT_PLUGIN_CLOUD_PROD_KEYWORDS="prod,production,prd"
POWERKIT_PLUGIN_CLOUD_CACHE_TTL="120"

# --- cloudstatus ---
POWERKIT_PLUGIN_CLOUDSTATUS_ICON="☁️"
POWERKIT_PLUGIN_CLOUDSTATUS_PROVIDERS="aws,azure,gcp,cloudflare"
POWERKIT_PLUGIN_CLOUDSTATUS_FORMAT="icon_symbol"
POWERKIT_PLUGIN_CLOUDSTATUS_SEPARATOR="|"
POWERKIT_PLUGIN_CLOUDSTATUS_SYMBOLS="simple"
POWERKIT_PLUGIN_CLOUDSTATUS_TIMEOUT="5"
POWERKIT_PLUGIN_CLOUDSTATUS_CACHE_TTL="7200"
POWERKIT_PLUGIN_CLOUDSTATUS_ISSUES_ONLY="true"
POWERKIT_PLUGIN_CLOUDSTATUS_WARNING_THRESHOLD="0"
POWERKIT_PLUGIN_CLOUDSTATUS_CRITICAL_THRESHOLD="0"

# --- cpu ---
POWERKIT_PLUGIN_CPU_ICON=$'\uf4bc'
POWERKIT_PLUGIN_CPU_CACHE_TTL="5"
POWERKIT_PLUGIN_CPU_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_CPU_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"

# --- gpu ---
POWERKIT_PLUGIN_GPU_ICON=$'\uf1b2'
POWERKIT_PLUGIN_GPU_ICON_NVIDIA=$'\uf110d'
POWERKIT_PLUGIN_GPU_ICON_AMD=$'\uf2db'
POWERKIT_PLUGIN_GPU_ICON_INTEL=$'\ue73d'
POWERKIT_PLUGIN_GPU_ICON_APPLE=$'\uf179'
POWERKIT_PLUGIN_GPU_SHOW_MEMORY="true"
POWERKIT_PLUGIN_GPU_CACHE_TTL="5"
POWERKIT_PLUGIN_GPU_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_GPU_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"

# --- datetime ---
POWERKIT_PLUGIN_DATETIME_ICON=$'\uf073'
POWERKIT_PLUGIN_DATETIME_FORMAT="datetime"
POWERKIT_PLUGIN_DATETIME_TIMEZONE=""
POWERKIT_PLUGIN_DATETIME_SHOW_WEEK="false"
POWERKIT_PLUGIN_DATETIME_SEPARATOR=" "

# --- disk ---
POWERKIT_PLUGIN_DISK_ICON=$'\uf0a0'
POWERKIT_PLUGIN_DISK_MOUNT="/"
POWERKIT_PLUGIN_DISK_FORMAT="percent"
POWERKIT_PLUGIN_DISK_CACHE_TTL="120"
POWERKIT_PLUGIN_DISK_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_DISK_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"

# --- external_ip ---
POWERKIT_PLUGIN_EXTERNAL_IP_ICON="󰩟"
POWERKIT_PLUGIN_EXTERNAL_IP_CACHE_TTL="600"

# --- git ---
POWERKIT_PLUGIN_GIT_ICON=$'\uf1d2'
POWERKIT_PLUGIN_GIT_CACHE_TTL="15"
POWERKIT_PLUGIN_GIT_MODIFIED_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_GIT_MODIFIED_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"

# --- github ---
POWERKIT_PLUGIN_GITHUB_ICON=$'\ue709'
POWERKIT_PLUGIN_GITHUB_REPOS="fabioluciano/tmux-powerkit"
POWERKIT_PLUGIN_GITHUB_FILTER_USER=""
POWERKIT_PLUGIN_GITHUB_SHOW_ISSUES="on"
POWERKIT_PLUGIN_GITHUB_SHOW_PRS="on"
POWERKIT_PLUGIN_GITHUB_SHOW_COMMENTS="off"
POWERKIT_PLUGIN_GITHUB_ICON_ISSUE=$'\uf41b'
POWERKIT_PLUGIN_GITHUB_ICON_PR=$'\uf407'
POWERKIT_PLUGIN_GITHUB_TOKEN="${GITHUB_TOKEN:-}"
POWERKIT_PLUGIN_GITHUB_CACHE_TTL="300"
POWERKIT_PLUGIN_GITHUB_FORMAT="compact"
POWERKIT_PLUGIN_GITHUB_WARNING_THRESHOLD="10"
POWERKIT_PLUGIN_GITHUB_SEPARATOR="$_DEFAULT_SEPARATOR"

# --- gitlab ---
POWERKIT_PLUGIN_GITLAB_URL="https://gitlab.com"
POWERKIT_PLUGIN_GITLAB_ICON=$'\uf296'
POWERKIT_PLUGIN_GITLAB_REPOS="gitlab-org/gitlab"
POWERKIT_PLUGIN_GITLAB_SHOW_ISSUES="on"
POWERKIT_PLUGIN_GITLAB_SHOW_MRS="on"
POWERKIT_PLUGIN_GITLAB_ICON_ISSUE=$'\uf41b'
POWERKIT_PLUGIN_GITLAB_ICON_MR=$'\uf407'
POWERKIT_PLUGIN_GITLAB_TOKEN=""
POWERKIT_PLUGIN_GITLAB_CACHE_TTL="300"
POWERKIT_PLUGIN_GITLAB_WARNING_THRESHOLD="10"
POWERKIT_PLUGIN_GITLAB_SEPARATOR="$_DEFAULT_SEPARATOR"

# --- bitbucket ---
POWERKIT_PLUGIN_BITBUCKET_URL="https://api.bitbucket.org/2.0"
POWERKIT_PLUGIN_BITBUCKET_ICON=$'\uf171'
POWERKIT_PLUGIN_BITBUCKET_REPOS="workspace/repo_slug"
POWERKIT_PLUGIN_BITBUCKET_SHOW_ISSUES="on"
POWERKIT_PLUGIN_BITBUCKET_SHOW_PRS="on"
POWERKIT_PLUGIN_BITBUCKET_ICON_ISSUE=$'\uf41b'
POWERKIT_PLUGIN_BITBUCKET_ICON_PR=$'\uf407'
POWERKIT_PLUGIN_BITBUCKET_TOKEN=""
POWERKIT_PLUGIN_BITBUCKET_CACHE_TTL="300"
POWERKIT_PLUGIN_BITBUCKET_WARNING_THRESHOLD="10"
POWERKIT_PLUGIN_BITBUCKET_SEPARATOR="$_DEFAULT_SEPARATOR"

# --- hostname ---
POWERKIT_PLUGIN_HOSTNAME_ICON="󰍹"
POWERKIT_PLUGIN_HOSTNAME_FORMAT="short"

# --- kubernetes ---
POWERKIT_PLUGIN_KUBERNETES_ICON=$'\ue81d'
POWERKIT_PLUGIN_KUBERNETES_DISPLAY_MODE="connected"
POWERKIT_PLUGIN_KUBERNETES_SHOW_NAMESPACE="false"
POWERKIT_PLUGIN_KUBERNETES_CONNECTIVITY_TIMEOUT="2"
POWERKIT_PLUGIN_KUBERNETES_CONNECTIVITY_CACHE_TTL="120"
POWERKIT_PLUGIN_KUBERNETES_CACHE_TTL="60"
# Kubernetes: C-g for conteGxt (context), C-s for nameSpace - free keys
POWERKIT_PLUGIN_KUBERNETES_CONTEXT_SELECTOR_KEY="C-g"
POWERKIT_PLUGIN_KUBERNETES_CONTEXT_SELECTOR_WIDTH="$_DEFAULT_POPUP_SIZE"
POWERKIT_PLUGIN_KUBERNETES_CONTEXT_SELECTOR_HEIGHT="$_DEFAULT_POPUP_SIZE"
POWERKIT_PLUGIN_KUBERNETES_NAMESPACE_SELECTOR_KEY="C-s"
POWERKIT_PLUGIN_KUBERNETES_NAMESPACE_SELECTOR_WIDTH="$_DEFAULT_POPUP_SIZE"
POWERKIT_PLUGIN_KUBERNETES_NAMESPACE_SELECTOR_HEIGHT="$_DEFAULT_POPUP_SIZE"

# --- loadavg ---
POWERKIT_PLUGIN_LOADAVG_ICON="󱦟"
POWERKIT_PLUGIN_LOADAVG_FORMAT="1"
POWERKIT_PLUGIN_LOADAVG_CACHE_TTL="10"
POWERKIT_PLUGIN_LOADAVG_WARNING_THRESHOLD_MULTIPLIER="2"
POWERKIT_PLUGIN_LOADAVG_CRITICAL_THRESHOLD_MULTIPLIER="4"

# --- memory ---
POWERKIT_PLUGIN_MEMORY_ICON=$'\uefc5'
POWERKIT_PLUGIN_MEMORY_FORMAT="percent"
POWERKIT_PLUGIN_MEMORY_CACHE_TTL="5"
POWERKIT_PLUGIN_MEMORY_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_MEMORY_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"

# --- microphone ---
POWERKIT_PLUGIN_MICROPHONE_ICON=$'\ued03'
POWERKIT_PLUGIN_MICROPHONE_MUTED_ICON=$'\uefc6'
POWERKIT_PLUGIN_MICROPHONE_CACHE_TTL="2"
POWERKIT_PLUGIN_MICROPHONE_ACTIVE_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_MICROPHONE_ACTIVE_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"
POWERKIT_PLUGIN_MICROPHONE_MUTED_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_MICROPHONE_MUTED_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"

# --- network ---
POWERKIT_PLUGIN_NETWORK_ICON="󰛳"
POWERKIT_PLUGIN_NETWORK_INTERFACE=""
POWERKIT_PLUGIN_NETWORK_CACHE_TTL="5"
POWERKIT_PLUGIN_NETWORK_THRESHOLD="0"

# --- nowplaying ---
POWERKIT_PLUGIN_NOWPLAYING_ICON="󰝚"
POWERKIT_PLUGIN_NOWPLAYING_FORMAT="%artist% - %track%"
POWERKIT_PLUGIN_NOWPLAYING_MAX_LENGTH="$_DEFAULT_MAX_LENGTH"
POWERKIT_PLUGIN_NOWPLAYING_NOT_PLAYING=""
POWERKIT_PLUGIN_NOWPLAYING_BACKEND="auto"
POWERKIT_PLUGIN_NOWPLAYING_IGNORE_PLAYERS="IGNORE"
POWERKIT_PLUGIN_NOWPLAYING_CACHE_TTL="5"

# --- packages ---
POWERKIT_PLUGIN_PACKAGES_ICON=$'\ueb29'
POWERKIT_PLUGIN_PACKAGES_BACKEND="auto"
POWERKIT_PLUGIN_PACKAGES_BREW_OPTIONS="--greedy"
POWERKIT_PLUGIN_PACKAGES_CACHE_TTL="3600"

# --- smartkey ---
POWERKIT_PLUGIN_SMARTKEY_ICON=$'\uf084'
POWERKIT_PLUGIN_SMARTKEY_WAITING_ICON=$'\ue23f'
POWERKIT_PLUGIN_SMARTKEY_WAITING_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_SMARTKEY_WAITING_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"
POWERKIT_PLUGIN_SMARTKEY_CACHE_TTL="2"
POWERKIT_PLUGIN_SMARTKEY_SHOW_WHEN_INACTIVE="false"

# --- temperature ---
POWERKIT_PLUGIN_TEMPERATURE_ICON=$'\uf2c7'
POWERKIT_PLUGIN_TEMPERATURE_UNIT="C"
POWERKIT_PLUGIN_TEMPERATURE_SOURCE="cpu"
POWERKIT_PLUGIN_TEMPERATURE_CACHE_TTL="10"
POWERKIT_PLUGIN_TEMPERATURE_WARNING_THRESHOLD="60"
POWERKIT_PLUGIN_TEMPERATURE_CRITICAL_THRESHOLD="80"
POWERKIT_PLUGIN_TEMPERATURE_HIDE_BELOW_THRESHOLD=""

# --- uptime ---
POWERKIT_PLUGIN_UPTIME_ICON=$'\ue382'
POWERKIT_PLUGIN_UPTIME_CACHE_TTL="300"

# --- volume ---
POWERKIT_PLUGIN_VOLUME_ICON=$'\uf028'
POWERKIT_PLUGIN_VOLUME_ICON_MUTED=$'\ueee8'
POWERKIT_PLUGIN_VOLUME_ICON_LOW=$'\uf027'
POWERKIT_PLUGIN_VOLUME_ICON_MEDIUM=$'\uf028'
POWERKIT_PLUGIN_VOLUME_MUTED_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_VOLUME_MUTED_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"
POWERKIT_PLUGIN_VOLUME_LOW_THRESHOLD="30"
POWERKIT_PLUGIN_VOLUME_MEDIUM_THRESHOLD="70"
POWERKIT_PLUGIN_VOLUME_CACHE_TTL="5"

# --- vpn ---
POWERKIT_PLUGIN_VPN_ICON=$'\ue672'
POWERKIT_PLUGIN_VPN_ICON_DISCONNECTED="󰫞"
POWERKIT_PLUGIN_VPN_SHOW_NAME="true"
POWERKIT_PLUGIN_VPN_SHOW_IP="false"
POWERKIT_PLUGIN_VPN_SHOW_WHEN_DISCONNECTED="false"
POWERKIT_PLUGIN_VPN_MAX_LENGTH="20"
POWERKIT_PLUGIN_VPN_CACHE_TTL="30"

# --- weather ---
POWERKIT_PLUGIN_WEATHER_ICON=$'\uf0c2'
POWERKIT_PLUGIN_WEATHER_ICON_MODE="static"
POWERKIT_PLUGIN_WEATHER_LOCATION=""
POWERKIT_PLUGIN_WEATHER_UNIT=""
POWERKIT_PLUGIN_WEATHER_FORMAT="minimal"
POWERKIT_PLUGIN_WEATHER_CACHE_TTL="900"

# --- wifi ---
POWERKIT_PLUGIN_WIFI_ICON="󰤨"
POWERKIT_PLUGIN_WIFI_ICON_DISCONNECTED="󰤭"
POWERKIT_PLUGIN_WIFI_DISCONNECTED_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_WIFI_DISCONNECTED_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"
POWERKIT_PLUGIN_WIFI_SHOW_SSID="true"
POWERKIT_PLUGIN_WIFI_SHOW_IP="false"
POWERKIT_PLUGIN_WIFI_SHOW_SIGNAL="false"
POWERKIT_PLUGIN_WIFI_HIDE_WHEN_CONNECTED="false"
POWERKIT_PLUGIN_WIFI_CACHE_TTL="30"

# --- ping ---
POWERKIT_PLUGIN_PING_ICON=$'\uf012'
POWERKIT_PLUGIN_PING_HOST="8.8.8.8"
POWERKIT_PLUGIN_PING_COUNT="1"
POWERKIT_PLUGIN_PING_TIMEOUT="2"
POWERKIT_PLUGIN_PING_UNIT="ms"
POWERKIT_PLUGIN_PING_CACHE_TTL="30"
POWERKIT_PLUGIN_PING_WARNING_THRESHOLD="100"
POWERKIT_PLUGIN_PING_CRITICAL_THRESHOLD="300"

# --- ssh ---
POWERKIT_PLUGIN_SSH_ICON=$'\uf489'
POWERKIT_PLUGIN_SSH_ACTIVE_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_SSH_ACTIVE_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_SSH_FORMAT="auto"
POWERKIT_PLUGIN_SSH_TEXT="SSH"
POWERKIT_PLUGIN_SSH_SHOW_WHEN_LOCAL="false"
POWERKIT_PLUGIN_SSH_DETECTION_MODE="current"

# --- fan ---
POWERKIT_PLUGIN_FAN_ICON=$'\uefa7'
POWERKIT_PLUGIN_FAN_ICON_FAST=$'\uf421'
POWERKIT_PLUGIN_FAN_SOURCE="auto"
POWERKIT_PLUGIN_FAN_FORMAT="krpm"
POWERKIT_PLUGIN_FAN_CACHE_TTL="10"
POWERKIT_PLUGIN_FAN_HIDE_WHEN_IDLE="false"
POWERKIT_PLUGIN_FAN_SELECTION="active"
POWERKIT_PLUGIN_FAN_SEPARATOR="$_DEFAULT_SEPARATOR"
POWERKIT_PLUGIN_FAN_WARNING_THRESHOLD="3000"
POWERKIT_PLUGIN_FAN_CRITICAL_THRESHOLD="5000"
POWERKIT_PLUGIN_FAN_SHOW_WHEN_UNAVAILABLE="false"
POWERKIT_PLUGIN_FAN_PLACEHOLDER="--"

# --- timezones ---
POWERKIT_PLUGIN_TIMEZONES_ICON=$'\uf0ac'
POWERKIT_PLUGIN_TIMEZONES_ZONES=""
POWERKIT_PLUGIN_TIMEZONES_FORMAT="%H:%M"
POWERKIT_PLUGIN_TIMEZONES_SEPARATOR="$_DEFAULT_SEPARATOR"
POWERKIT_PLUGIN_TIMEZONES_SHOW_LABEL="true"

# --- terraform ---
POWERKIT_PLUGIN_TERRAFORM_ICON=$'\ue69a'
POWERKIT_PLUGIN_TERRAFORM_TOOL="terraform"
POWERKIT_PLUGIN_TERRAFORM_SHOW_ONLY_IN_DIR="true"
POWERKIT_PLUGIN_TERRAFORM_SHOW_PENDING="true"
POWERKIT_PLUGIN_TERRAFORM_WARN_ON_PROD="true"
POWERKIT_PLUGIN_TERRAFORM_PROD_KEYWORDS="prod,production,prd"
POWERKIT_PLUGIN_TERRAFORM_PROD_ACCENT_COLOR="$_DEFAULT_ERROR"
POWERKIT_PLUGIN_TERRAFORM_PROD_ACCENT_COLOR_ICON="$_DEFAULT_ERROR_ICON"
POWERKIT_PLUGIN_TERRAFORM_PENDING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_TERRAFORM_PENDING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
# Terraform: C-f for terraForm workspace - free key
POWERKIT_PLUGIN_TERRAFORM_WORKSPACE_KEY="C-f"
POWERKIT_PLUGIN_TERRAFORM_CACHE_TTL="30"

# =============================================================================
# APPLY INHERITED DEFAULTS (DRY)
# =============================================================================
# Plugins with thresholds get warning/critical colors automatically
# =============================================================================

# Standard plugins (no thresholds)
for _p in audiodevices bitwarden bluetooth brightness camera cloud datetime \
          external_ip git hostname kubernetes network nowplaying \
          packages smartkey uptime vpn weather wifi ssh timezones; do
    _plugin_defaults "$_p"
done

# Plugins with warning/critical thresholds
for _p in battery cloudstatus cpu gpu disk github gitlab bitbucket \
          loadavg memory microphone temperature volume ping fan terraform; do
    _plugin_defaults "$_p" "thresholds"
done

unset _p

# =============================================================================
# SYSTEM CONSTANTS (used by plugins)
# =============================================================================

# Byte sizes (used by disk, memory, network, gpu)
POWERKIT_BYTE_KB=1024
POWERKIT_BYTE_MB=1048576
POWERKIT_BYTE_GB=1073741824
POWERKIT_BYTE_TB=1099511627776

# Cache keybinding (prefix + Ctrl+d for Delete cache) - free key
POWERKIT_PLUGIN_CACHE_CLEAR_KEY="C-d"

# Timing constants (used by cpu, network)
POWERKIT_TIMING_CPU_SAMPLE="0.1"
POWERKIT_TIMING_CACHE_INTERFACE="300"
POWERKIT_TIMING_CACHE_LONG="60"          # Long-lived cache for delta calculations (network prev data)
POWERKIT_TIMING_MIN_DELTA="0.1"
POWERKIT_TIMING_FALLBACK="1"

# iostat (used by cpu)
POWERKIT_IOSTAT_COUNT="2"
POWERKIT_IOSTAT_CPU_FIELD="6"
POWERKIT_IOSTAT_BASELINE="100"

# Performance limits (used by cpu)
POWERKIT_PERF_CPU_PROCESS_LIMIT="50"

# Telemetry (optional performance tracking)
POWERKIT_TELEMETRY_ENABLED="false"
POWERKIT_TELEMETRY_LOG_FILE=""
POWERKIT_TELEMETRY_SLOW_THRESHOLD="500"
POWERKIT_TELEMETRY_TRACK_CACHE_HITS="true"
POWERKIT_TELEMETRY_MAX_LOG_SIZE="1048576"

# Fallback colors
POWERKIT_FALLBACK_STATUS_BG="#292e42"

# ANSI colors (used by helpers)
POWERKIT_ANSI_BOLD='\033[1m'
POWERKIT_ANSI_DIM='\033[2m'
POWERKIT_ANSI_RESET='\033[0m'
POWERKIT_ANSI_GREEN='\033[32m'
POWERKIT_ANSI_YELLOW='\033[33m'
POWERKIT_ANSI_BLUE='\033[34m'
POWERKIT_ANSI_CYAN='\033[36m'
